# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-02-12 10:47:40 +0300 by andrey:
gem "net-scp", "~> 1.2"
